-- Seeded test schema for postgres-studio.
-- Applied ONLY to $TEST_DATABASE_URL (see docs/agent-workflow.md § Safety).
--
-- Covers the shapes Phase 0–3 depend on:
--   1. self-FK             employees.manager_id -> employees.id
--   2. composite PK/FK     orders(shop_id, order_no) <- order_items
--   3. cascade pair        customers <- addresses (ON DELETE CASCADE)
--   4. multi-schema        app.projects / app.tasks / app.project_stats view
--   5. enum type           app.task_status
--   6. cross-schema FK     public.links -> app.projects
--   7. unique + secondary  customers.email unique, tasks_project_idx

drop schema if exists app cascade;

drop table if exists public.links,
  public.addresses,
  public.order_items,
  public.orders,
  public.customers,
  public.employees cascade;

create table public.employees (
  id integer generated by default as identity primary key,
  name text not null,
  manager_id integer references public.employees (id) on delete set null
);

create table public.orders (
  shop_id integer not null,
  order_no integer not null,
  total numeric(10, 2) not null default 0,
  delivery_address_id integer,
  primary key (shop_id, order_no)
);

create table public.order_items (
  id integer generated by default as identity primary key,
  shop_id integer not null,
  order_no integer not null,
  product text not null,
  quantity integer not null default 1,
  foreign key (shop_id, order_no)
    references public.orders (shop_id, order_no)
    on delete cascade
);

create table public.customers (
  id integer generated by default as identity primary key,
  email text not null unique
);

create table public.addresses (
  id integer generated by default as identity primary key,
  customer_id integer not null references public.customers (id) on delete cascade,
  line text not null
);

create schema app;

create type app.task_status as enum ('todo', 'doing', 'done');

create table app.projects (
  id integer generated by default as identity primary key,
  code text not null unique,
  budget numeric(12, 2)
);

create table app.tasks (
  id integer generated by default as identity primary key,
  project_id integer not null references app.projects (id) on delete cascade,
  title text not null,
  status app.task_status not null default 'todo',
  created_at timestamptz not null default now()
);

create index tasks_project_idx on app.tasks (project_id);

create index tasks_open_idx on app.tasks (project_id) where status = 'todo';

create view app.project_stats as
select p.id, p.code, count(t.id)::int as task_count
from app.projects p
left join app.tasks t on t.project_id = p.id
group by p.id, p.code;

create table public.links (
  id integer generated by default as identity primary key,
  project_id integer not null references app.projects (id) on delete cascade,
  url text not null
);

insert into public.employees (id, name, manager_id) values
  (1, 'Ada Lovelace', null),
  (2, 'Grace Hopper', 1),
  (3, 'Alan Turing', 1),
  (4, 'Linus Torvalds', 2);

insert into public.orders (shop_id, order_no, total) values
  (1, 100, 150.00),
  (1, 101, 60.00),
  (2, 100, 99.50);

insert into public.order_items (id, shop_id, order_no, product, quantity) values
  (1, 1, 100, 'keyboard', 2),
  (2, 1, 100, 'usb hub', 1),
  (3, 1, 101, 'mouse', 1),
  (4, 2, 100, 'monitor', 1),
  (5, 2, 100, 'cable', 3),
  (6, 1, 100, 'dock', 1);

insert into public.customers (id, email) values
  (1, 'ada@example.com'),
  (2, 'grace@example.com');

insert into public.addresses (id, customer_id, line) values
  (1, 1, '12 Analytical St'),
  (2, 1, '34 Mark I Ave'),
  (3, 2, '56 Compiler Rd'),
  (4, 1, '78 Second St');

insert into app.projects (id, code, budget) values
  (1, 'ALPHA', 1000.00),
  (2, 'BETA', null);

insert into app.tasks (id, project_id, title, status) values
  (1, 1, 'wire grid', 'done'),
  (2, 1, 'fk drawer', 'doing'),
  (3, 2, 'rollback log', 'todo');

insert into public.links (id, project_id, url) values
  (1, 1, 'https://example.com/alpha-spec'),
  (2, 1, 'https://example.com/alpha-notes');

-- Explicit-id inserts do not advance identity sequences; sync them so
-- auto-generated ids never collide with seeded rows.
select setval(pg_get_serial_sequence('public.employees', 'id'), (select max(id) from public.employees));
select setval(pg_get_serial_sequence('public.order_items', 'id'), (select max(id) from public.order_items));
select setval(pg_get_serial_sequence('public.customers', 'id'), (select max(id) from public.customers));
select setval(pg_get_serial_sequence('public.addresses', 'id'), (select max(id) from public.addresses));
select setval(pg_get_serial_sequence('public.links', 'id'), (select max(id) from public.links));
select setval(pg_get_serial_sequence('app.projects', 'id'), (select max(id) from app.projects));
select setval(pg_get_serial_sequence('app.tasks', 'id'), (select max(id) from app.tasks));
