-- Seeded test schema for postgres-studio.
-- Applied ONLY to $TEST_DATABASE_URL (see docs/agent-workflow.md § Safety).
--
-- Covers the three shapes Phase 0–3 depend on:
--   1. self-FK            employees.manager_id -> employees.id
--   2. composite PK/FK    orders(shop_id, order_no) <- order_items
--   3. cascade pair       customers <- addresses (ON DELETE CASCADE)

drop table if exists public.addresses,
  public.order_items,
  public.orders,
  public.customers,
  public.employees cascade;

create table public.employees (
  id integer generated by default as identity primary key,
  name text not null,
  manager_id integer references public.employees (id) on delete set null
);

create table public.orders (
  shop_id integer not null,
  order_no integer not null,
  total numeric(10, 2) not null default 0,
  primary key (shop_id, order_no)
);

create table public.order_items (
  id integer generated by default as identity primary key,
  shop_id integer not null,
  order_no integer not null,
  product text not null,
  quantity integer not null default 1,
  foreign key (shop_id, order_no)
    references public.orders (shop_id, order_no)
    on delete cascade
);

create table public.customers (
  id integer generated by default as identity primary key,
  email text not null unique
);

create table public.addresses (
  id integer generated by default as identity primary key,
  customer_id integer not null references public.customers (id) on delete cascade,
  line text not null
);

insert into public.employees (id, name, manager_id) values
  (1, 'Ada Lovelace', null),
  (2, 'Grace Hopper', 1),
  (3, 'Alan Turing', 1),
  (4, 'Linus Torvalds', 2);

insert into public.orders (shop_id, order_no, total) values
  (1, 100, 150.00),
  (1, 101, 60.00),
  (2, 100, 99.50);

insert into public.order_items (id, shop_id, order_no, product, quantity) values
  (1, 1, 100, 'keyboard', 2),
  (2, 1, 100, 'usb hub', 1),
  (3, 1, 101, 'mouse', 1),
  (4, 2, 100, 'monitor', 1),
  (5, 2, 100, 'cable', 3);

insert into public.customers (id, email) values
  (1, 'ada@example.com'),
  (2, 'grace@example.com');

insert into public.addresses (id, customer_id, line) values
  (1, 1, '12 Analytical St'),
  (2, 1, '34 Mark I Ave'),
  (3, 2, '56 Compiler Rd');
